### ISSUE TITLE
Date default to local date?

### ISSUE THREAD

**Issue by mark-meibers-cr** [soulim/ember-cli-bootstrap-datepicker#15] opened 2015-03-09 21:50 UTC
Im new to ember and to github, so sorry if this is the wrong place to post/ask this.  If it is, let me know the appropriate place.

When I visit your demo page, the date I pick, is the date displayed in the input field.  However, when I implement ember-bootstrap-datepicker, when I choose a date, its always a day behind.  I'm working on an internal use only app and would like the date to always display the date picked with no UTC conversion.  Is this possible?

**Comment by mark-meibers-cr** [comment] 2015-03-09 21:55
If I have a field that binds to the same input, the second field displays the day I picked, its only the input field that the date-picker displays that is incorrect (a day behind).

example:
{{bootstrap-datepicker value=expires_at autoclose=true class="form-control datepicker"}}
//displays the the date as 1 day behind date selected

//second field on page that shows a preview shows correct date:
{{short-date expires_at}}
// short-date is just a formatter to display the date in a different format.

This behavior is confusing my users so I'm hoping Im over looking a way to override it.

Thanks in advance.

**Comment by btecu** [comment] 2015-03-12 16:14
This is definitely a bug and you can now see it on the demo page as well.
It always selects the day before the one you chose. If you select the same day a second time, somehow it works correctly.

I think something has changed in `bootstrap-datepicker` from `1.3.1` to `1.4.0`.

**Comment by soulim** [comment] 2015-03-12 16:24
Hey guys! I'm sorry for the late response. Seems like I need more details to reproduce this problem because demo page works fine for me :confused: 

I guess the problem might be somewhere in `bootstrap-datepicker` itself because the add-on is just a thin wrapper around this library. Anyway I would be happy to double check everything and find out what causes this issue with input field.

In what timezone you are? I'm in Berlin, Germany (UTC+1).

**Comment by btecu** [comment] 2015-03-12 16:27
Can you try changing to `UTC-6` ?. The demo page works for you?

**Comment by soulim** [comment] 2015-03-12 17:00
Yep. When the timezone is set to UTC-6, I'm able to reproduce the issue.

![screen shot 2015-03-12 at 10 55 54 am](https://cloud.githubusercontent.com/assets/2370/6623124/0349d69c-c8af-11e4-8fd8-e4d2472506ed.png)

On the screenshot I'm trying to choose March 2, but the calendar is set on March 1. Will take a look into details.

**Comment by soulim** [comment] 2015-03-12 17:11
There's an open issue https://github.com/eternicode/bootstrap-datepicker/issues/761 that sounds pretty close to the problem you have guys.

**Comment by soulim** [comment] 2015-03-12 17:23
However `bootstrap-datepicker` [demo page][1] works perfectly fine. So now it's time to debug things :smile: 

[1]: http://eternicode.github.io/bootstrap-datepicker/

**Comment by btecu** [comment] 2015-03-12 18:33
You should note that their demo page seems to be using version 1.4.1, although I'm not sure if it would be broken in version 1.5.

**Comment by soulim** [comment] 2015-03-13 06:58
Okay! The bug has been fixed in https://github.com/soulim/ember-cli-bootstrap-datepicker/commit/805814772da1cb7bd61872068e8712a16d8fc3cf. I was wrong, that was the add-on who caused the problem.

Could you please play with the datepicker on [demo page][1] and check if everything works correctly? Thank you for your help! :smile: 

If the add-on works fine for you on the demo page, I'll immediately release a new version to fix the bug for everyone.
[1]: http://sul.im/ember-cli-bootstrap-datepicker/

**Comment by btecu** [comment] 2015-03-13 12:04
It works now! Thanks a lot.

**Comment by soulim** [comment] 2015-03-13 13:32
Perfect! The version 0.3.3 has been released - https://github.com/soulim/ember-cli-bootstrap-datepicker/releases/tag/v0.3.3.

Thank you @mark-meibers-cr and @btecu for you help and support :smile:

**Closed** 2015-03-13 13:44 UTC
Labels: bug
